#:kivy 2.3.0
<ClickableImage>:
    allow_stretch: True
    size_hint_x: 0.1
    size: '30dp', '30dp'

<MyScreenManager>:
    LoginScreen:
    LoginSecondScreen: 
    HomeApp:
    RegistrationScreen: 
    AdminScreen:
    QueueScreen:
    DataLansiaScreen:
    DaftarScreen:
    PatientList:
    UserList:
    ImunisasiScreen:
    DatabalitaScreen:
    AdminAntrianScreen:
    RiwayatImunScreen:
    AddBalitaScreen:
    AddLansiaScreen:
    ProfilScreen:
    DaftarbalitaScreen:



